#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
scheme: Mist
# scheme: Pisces
# scheme: Gemini

darkmode: true


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  sidebar: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-home

  Documentation:
    default: /docs/ || fa fa-book

    Mechanical Design:
      default: /mechanicaldesign/ || fa fa-cogs
      3D Explorer: /3dexplorer || fa fa-download
      Motion System: /motionsystem || fa fa-upload
      Frame Design: /framedesign || fa fa-wrench
      Manufacturing: /manufacturing || fa fa-history

    Printer Firmware:
      default: /printfirmware/ || fab fa-uncharted
      # Sidebar: /sidebar.html || fa fa-bars
      # Footer: /footer.html || fa fa-sticky-note
      # Posts: /posts.html || fa fa-paragraph
      # Custom Pages: /custom-pages.html || fa fa-swatchbook
      # Miscellaneous: /miscellaneous.html || fa fa-university
      # SEO: /seo.html || fa fa-external-link-square-alt
      # i18n: /internationalization.html || fa fa-globe-asia

    Electronics:
      default: /electronics/ || fa fa-car-battery
      Schematics: /schematics.html || fa fa-square-root-alt
      PCBs: /pcbs.html || fa fa-comment-alt
      Motors: /motors.html || fa fa-gift
      Heating: /heating.html || fa fa-chart-pie
      Switch Cabinet: /switchcabinet.html || fa fa-chart-pie
      # Search Services: /search-services.html || fab fa-algolia
      # Chat Services: /chat-services.html || fa fa-comments
      # External Libraries: /external-libraries.html || fa fa-lightbulb

    Print Algorithms:
      default: /printalgorithms/ || fas fa-print
      Basic Printing: /basic.html || fa fa-cube
      Not The Brightest Bulb: /ntbb.html || fa fa-cube
      Algoritmic Vasemode: /algvase.html || fa fa-signal
      # Group Pictures: /group-pictures.html || fa fa-images
      # Label: /label.html || fa fa-hat-wizard
      # Link Grid: /link-grid.html || fa fa-grip-vertical
      # Mermaid: /mermaid.html || fa fa-project-diagram
      # Note: /note.html || fa fa-adjust
      # PDF: /pdf.html || fa fa-file-pdf
      # Tabs: /tabs.html || fa fa-columns

  References: /references/ || fa fa-flask
  Sponsors: /sponsors/ || fa fa-hands-helping
  Archives: /archives/ || fa fa-archive
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: false


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 12
  offset: 12

avatar:
  url: /images/HF_Logo01.png
  rounded: true

social:
  GitHub: https://github.com/next-theme || fab fa-github
  RSS: /atom.xml || fa fa-rss
  Gitter: https://gitter.im/hexo-next || fab fa-gitter

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: false
  wrap: true


# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2018
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: HUGEFANCY


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_total: true

post_edit:
  enable: false
  url: https://github.com/next-theme/theme-next-docs/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: false
  permalink: https://github.com/next-theme/hexo-theme-next
  title: Fork NexT on GitHub


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google_site_verification: 5AUIVYTbHIAuz-eQtxSfZbWW5eg9_EVZMSQycIuXrG0


# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  mathjax:
    enable: true
    tags: ams

pjax: false

mediumzoom: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: false

disqus:
  enable: false
  shortname: next-theme
  count: true


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

google_analytics:
  tracking_id: UA-108155018-3


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  async: true

vendors:
  internal: jsdelivr

# JavaScript 3D library.
# Dependencies: https://github.com/next-theme/hexo-next-three
three:
  enable: true
  defer: true
  cdn:
  waves:
    enable: false
    cdn:
  lines:
    enable: false
    cdn:
  sphere:
    enable: false
    cdn: